# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include: 
      - v2/dev
      - v2/feature/*
      - v2/hotfix/*
      - v2/release/*
  tags:
    include:
      - v*

variables:
  - name: 'vmImageName'
    value: 'vs2017-win2016'
  - name: 'nuGetOrgServiceCreds'
    value: 'NuGet.org (Vendr.Contrib)'
  - name: 'packageName'
    value: 'Vendr.Contrib.Reviews'

stages:

  - stage: build
    displayName: 'Build'
    dependsOn: [  ]
    pool:
      vmImage: $(vmImageName)
    jobs:

      - job: Build
        displayName: 'Build'
        dependsOn: [ ]
        steps:

          - task: CmdLine@2
            inputs:
              script: './build.cmd Pack'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: artifacts

  - stage: deploy
    displayName: 'Deploy'
    condition: succeeded()
    dependsOn: [ build ]

    jobs:
    - deployment: deploy
      displayName: Deploy
      environment: 'development'
      pool:
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps: 

              # Unstable Deploy
              - task: NuGetCommand@2
                displayName: 'Deploy to unstable feed'
                inputs:
                  command: 'push'
                  packagesToPush: '$(Pipeline.Workspace)/artifacts/**/*.nupkg;!$(Pipeline.Workspace)/artifacts/**/*.snupkg'
                  nuGetFeedType: 'internal'
                  publishVstsFeed: 'b7810adb-d090-464a-84f1-8e6cd318c30c/fbc2bb03-9eff-453e-bb77-bdc141666fc5'

              # Release Deploy
              - task: UseDotNet@2
                condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/v'))
                inputs:
                  version: 3.0.100

              - powershell: |
                  # get the umbraco package file (assumes there is just one zip file package)
                  $f = (Get-ChildItem -Path "$(Pipeline.Workspace)\artifacts\packages\*" -File -Include $(packageName).*.zip | Select-Object -First 1).FullName
                  # assign the filename to a variable        
                  echo "$f" 
                  echo "##vso[task.setvariable variable=umbracoPackageFile]$f" 
                displayName: 'Get Umbraco Package path'
                condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/v'))

              - task: NuGetCommand@2
                displayName: 'Deploy to NuGet.org'
                condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/v'))
                inputs:
                  command: push
                  nuGetFeedType: external
                  packagesToPush: '$(Pipeline.Workspace)/artifacts/**/*.nupkg;!$(Pipeline.Workspace)/artifacts/**/*.snupkg'
                  publishFeedCredentials: '$(nuGetOrgServiceCreds)'

              - script: |
                  dotnet tool install --global Umbraco.Tools.Packages
                condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/v'))
                displayName: 'Install UmbPack'

              - script: |
                  umbpack push $(umbracoPackageFile) -k %OUR_UMBRACO_API_KEY% -w v8170,v900,v910,v920 -c true -a $(packageName).2.*.zip 
                condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/v'))
                displayName: 'Deploy to Our Umbraco'
                env:
                  OUR_UMBRACO_API_KEY: $(our-umbraco-api-key)